name: Docker
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
concurrency: 
  group: ci
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata for Lite Image
        id: meta-lite
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/npalladium/k8s-lite-debug-image
      - name: Build and push Lite Docker image
        id: build-and-push-lite
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-lite.outputs.tags }}
          labels: ${{ steps.meta-lite.outputs.labels }}
          file: lite/Dockerfile
      - name: Extract Docker metadata for AWS Image
        id: meta-aws
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/npalladium/k8s-aws-debug-image
      - name: Build and push AWS Docker image
        id: build-and-push-aws
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-aws.outputs.tags }}
          labels: ${{ steps.meta-aws.outputs.labels }}
          file: aws/Dockerfile
      - name: Extract Docker metadata for stress Image
        id: meta-stress
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/npalladium/k8s-stress-debug-image
      - name: Build and push stress Docker image
        id: build-and-push-stress
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-stress.outputs.tags }}
          labels: ${{ steps.meta-stress.outputs.labels }}
          file: stress/Dockerfile
